### ISSUE TITLE
Vulnerability in fresh

### ISSUE THREAD

**Issue by hieuhtr** [jshttp/fresh#28]
From snyk.io, we have **Regular Expression Denial of Service** (ReDoS) on this package

TL;DR: 

> Affected versions of this package are vulnerable to Regular expression Denial of Service (ReDoS) attacks. A Regular Expression (/ *, */) was used for parsing HTTP headers and take about 2 seconds matching time for 50k characters.

Please take a look and check, if true --> please fix it asap, because many packages are based on it

Source: https://snyk.io/vuln/npm:fresh:20170908

**Comment by dougwilson** [comment]
It's already fixed in 0.5.2 release. From that source:

> Remediation
> Upgrade fresh to version 0.5.2 or higher.

**Comment by hieuhtr** [comment]
Great, many thanks! 🎉

**Comment by dougwilson** [comment]
Fixed Sep 13, 2017 👍
