### ISSUE TITLE
Inadvertent reverse of 'no-cache' and 'no-store'

### ISSUE THREAD

**Issue by Univream** [jshttp/fresh#29]
As stated in the MDN docs the `no-cache` directive is used indicate that the client has a copy in the cache but needs to validate it with each request. `no-store` on the other hand will disable all caches. 

> no-cache
>      Forces caches to submit the request to the origin server for validation before releasing a cached copy.

This means that fresh should give back true inconjuction with theses headers:
var reqHeaders = {
    "if-none-match": "foo",
    "cache-control" : "no-cache" 
};

var resHeaders = {
    "etag" : "foo"
};

correct me if I'm wrong;

**Comment by dougwilson** [comment]
Can you link to the MDN article you are referencing?

**Comment by dougwilson** [comment]
At least based on what you pasted

> Forces caches to submit the request to the origin server for validation before releasing a cached copy.

The behavior of this module is correct; true = fresh and false = stale.

What you pasted says that it should bust the cache, right? As in this module should state stale (false), not fresh (true).

**Comment by dougwilson** [comment]
Issue #16 has more background if it helps.

**Comment by Univream** [comment]
Here is the [MDN article](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) as well as a [Google developer article](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching) which explains http caching.

`fresh` should give back true but it didn't (if Etag header and if-none-match header match, client cache is fresh)


No-store would mean that there is no cache, which makes the request stale, doesn't it?


var reqHeaders = {
    "if-none-match": "bar",
    "cache-control" : "no-store" 
};

var resHeaders = {
    "etag" : "bar"
};

fresh(reqHeaders, resHeaders); -> true

**Comment by dougwilson** [comment]
There are two different Cache-Control headers: one for requests and one for responses. This module only reads the Cache-Control for requests, not responses. The MDN article is only for the Cache-Control response header, which is not relevant here. That controls the behavior of the web client (browser) not the web server (node.js). There are different directives for each side with different meanings.
