### ISSUE TITLE
If-Modified-Since is not ignored if request contains If-None-Match

### ISSUE THREAD

**Issue by marco2216** [jshttp/fresh#35]
According to the latest [HTTP RFC](https://www.rfc-editor.org/rfc/rfc9110.html#name-if-none-match), 

> A recipient MUST ignore If-Modified-Since if the request contains an [If-None-Match](https://www.rfc-editor.org/rfc/rfc9110.html#field.if-none-match) header field; the condition in [If-None-Match](https://www.rfc-editor.org/rfc/rfc9110.html#field.if-none-match) is considered to be a more accurate replacement for the condition in If-Modified-Since, and the two are only combined for the sake of interoperating with older intermediaries that might not implement [If-None-Match](https://www.rfc-editor.org/rfc/rfc9110.html#field.if-none-match).

`fresh` does not ignore If-Modified-Since, it returns false if the If-Modified-Since is before last-modified. I would expect it to return true immediately if  If-None-Match matches the ETag header.

**Comment by dougwilson** [comment]
Ah, yes, it looks like this is a new change in the spec, as that requirement was not part of RFC 7232, AFAICT.

**Comment by marco2216** [comment]
I think it was?
![image](https://user-images.githubusercontent.com/4561482/215774723-cddf58b8-4925-4bee-a2a9-8cd16a02f41d.png)

**Comment by dougwilson** [comment]
Oh, you're right. That's why I said as far as I can tell. I guess I assumed it would be in the same section in both RFC, doh.

**Comment by marco2216** [comment]
If you'd like, I could try to create a PR addressing the issue?

**Comment by bigbigDreamer** [comment]
Hi, sorry to bother you. May I ask if there has been any progress on this matter, or what the follow-up plan is, or if there is a timeline? @dougwilson

**Comment by dougwilson** [comment]
Hi @bigbigDreamer apologies for that! It just got lost in the sea of notifications for me and then fell off more as I got some unrelated security reports I had to triage and working on fixing one of them currently. I think I already pushed up the changeset, so I will get a release made and pushed here.

**Comment by UlisesGascon** [comment]
> If you'd like, I could try to create a PR addressing the issue?

Hi @marco2216! Are you still interested in working on this PR? We've completed the migration to GitHub already :)

**Comment by bigbigDreamer** [comment]
> > If you'd like, I could try to create a PR addressing the issue?
> 
> Hi @marco2216! Are you still interested in working on this PR? We've completed the migration to GitHub already :)

Hi , I fix this, can u help me review #38
